#!/bin/bash
# Test script for VibeDB PostgreSQL compatibility

echo "=== VibeDB psql Test Script ==="
echo ""
echo "This script demonstrates basic SQL operations using psql with VibeDB."
echo ""
echo "First, start the VibeDB server in another terminal:"
echo "  cargo run -- --port 5433"
echo ""
echo "Then run these commands with psql:"
echo ""
echo "# Connect to VibeDB (use port 5433 to avoid conflicts with PostgreSQL)"
echo "psql -h localhost -p 5433 -U vibedb -d vibedb"
echo ""
echo "# Test queries (these will work):"
echo "SELECT * FROM users;"
echo "SELECT * FROM products;"
echo "INSERT INTO users (id, name, email, active) VALUES (1, 'Alice', 'alice@example.com', true);"
echo "INSERT INTO users (id, name, email, active) VALUES (2, 'Bob', 'bob@example.com', false);"
echo "SELECT * FROM users;"
echo "SELECT name, email FROM users WHERE active = true;"
echo ""
echo "# Note: CREATE TABLE is not supported through SQL yet"
echo "# Tables must be created programmatically when the server starts"
echo ""
echo "# Exit psql:"
echo "\\q"